import asyncio
import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from nanobot.agent.subagent import SubagentManager
from nanobot.bus.queue import MessageBus
from nanobot.session.manager import SessionManager


@pytest.fixture
def workspace(tmp_path):
    return tmp_path


@pytest.fixture
def session_manager(workspace):
    return SessionManager(workspace)


@pytest.fixture
def mock_provider():
    provider = MagicMock()
    provider.get_default_model.return_value = "test-model"
    provider.chat_with_retry = AsyncMock()
    return provider


@pytest.fixture
def message_bus():
    return MessageBus()


@pytest.mark.asyncio
async def test_subagent_trajectory_persistence(workspace, session_manager, mock_provider, message_bus):
    # 1. Prepare Mock LLM response sequence
    # Turn 1: calling the read_file tool
    tool_call = MagicMock()
    tool_call.id = "call_1"
    tool_call.name = "read_file"
    tool_call.arguments = {"path": "test.txt"}
    tool_call.to_openai_tool_call.return_value = {
        "id": "call_1",
        "type": "function",
        "function": {"name": "read_file", "arguments": '{"path": "test.txt"}'}
    }

    resp1 = MagicMock()
    resp1.has_tool_calls = True
    resp1.tool_calls = [tool_call]
    resp1.content = "Thinking about reading a file..."
    resp1.reasoning_content = "I need to check the file content first."
    resp1.thinking_blocks = ["I will use read_file."]

    # Turn 2: providing the final response
    resp2 = MagicMock()
    resp2.has_tool_calls = False
    resp2.content = "The file contains: hello world"
    resp2.reasoning_content = None
    resp2.thinking_blocks = []

    mock_provider.chat_with_retry.side_effect = [resp1, resp2]

    # 2. Initialize SubagentManager and start task
    manager = SubagentManager(
        provider=mock_provider,
        workspace=workspace,
        bus=message_bus,
        session_manager=session_manager,
        restrict_to_workspace=True
    )

    # Pre-create a test file for the tool to read
    (workspace / "test.txt").write_text("hello world")

    task_id = None

    # We need to intercept the task_id generated by spawn
    original_spawn = manager.spawn
    async def wrapped_spawn(*args, **kwargs):
        nonlocal task_id
        res = await original_spawn(*args, **kwargs)
        # Extract ID: "Subagent [...] started (id: abc12345)..."
        import re
        match = re.search(r"id: ([a-f0-9]+)", res)
        if match:
            task_id = match.group(1)
        return res

    manager.spawn = wrapped_spawn

    await manager.spawn(task="Read test.txt and tell me what's inside", label="Test Task")

    # Wait for background task completion
    while manager.get_running_count() > 0:
        await asyncio.sleep(0.1)

    # 3. Verify Session persistence
    assert task_id is not None
    session_key = f"subagent:{task_id}"
    
    # Reload from disk to verify persistence
    new_session_manager = SessionManager(workspace)
    session = new_session_manager.get_or_create(session_key)

    assert session.metadata["type"] == "subagent"
    assert session.metadata["label"] == "Test Task"
    
    # Verify message trajectory
    # index 0: system prompt
    # index 1: user task
    # index 2: assistant (tool call)
    # index 3: tool result
    # index 4: assistant (final response)
    msgs = session.messages
    assert len(msgs) >= 5
    assert msgs[0]["role"] == "system"
    assert "Read test.txt" in msgs[1]["content"]
    assert msgs[2]["role"] == "assistant"
    assert msgs[2]["tool_calls"][0]["function"]["name"] == "read_file"
    assert msgs[3]["role"] == "tool"
    assert "hello world" in msgs[3]["content"]
    assert msgs[4]["role"] == "assistant"
    assert "hello world" in msgs[4]["content"]
